name: CleanupEpicEnvironment
trigger: none

parameters:
  - name: branchName
    type: string

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
    - repository: fsm-akka-azure-pipelines
      type: github
      name: mehmetsalgar/fsm-akka-azure-pipelines
      endpoint: mehmetsalgar

stages:
  - stage: Deploy
    jobs:
      - template: cleanup-environment.yml@fsm-akka-azure-pipelines
        parameters:
          branchName: "feature/${{ parameters.branchName }}"
