name: Continuous Deployment Integration Helm Umbrella Chart
trigger:
  branches:
    include:
      - refs/heads/feature/*
  paths:
    exclude:
      - "azure/*.yml"

pool:
  vmImage: ubuntu-latest

variables:
  - group: HELM_VARIABLES
  - group: DOCKER_VARIABLES

resources:
  repositories:
    - repository: fsm-akka-azure-pipelines
      type: github
      name: mehmetsalgar/fsm-akka-azure-pipelines
      endpoint: mehmetsalgar

stages:
  - template: continuous-deployment-template.yml@self
    parameters:
      infrastructureSourceBranch: "development"
      buildType: "feature"
