name: helm_publish

trigger:
- development

pool:
  vmImage: ubuntu-latest

variables:
- group: HELM_VARIABLES
- group: DOCKER_VARIABLES

resources:
  repositories:
    - repository: fsm-akka-azure-pipelines
      type: github
      name: mehmetsalgar/fsm-akka-azure-pipelines
      endpoint: mehmetsalgar

stages:
  - stage: Build
    jobs:
      - template: helm-publish.yml@fsm-akka-azure-pipelines
        parameters:
          chartName: 'fsm-akka-helm-umbrella-chart-az'
