name: helm_publish

trigger:
- development

pool:
  vmImage: ubuntu-latest

variables:
- group: HELM_VARIABLES
- group: DOCKER_VARIABLES

jobs:
  - job: CalculateVersion
    displayName: Calculate Version
    pool:
      vmImage: ubuntu-latest
    steps:
     - checkout: self
       fetchDepth: 0
     - task: gitversion/setup@0
       displayName: Install GitVersion
       inputs:
        versionSpec: "5.x"
     - task: gitversion/execute@0
       name: calculateVersion
       displayName: Calculating version
       inputs:
        useConfigFile: True
        configFilePath: "GitVersion.yml"
  - job: Build
    displayName: Build
    dependsOn: CalculateVersion
    pool:
      vmImage: ubuntu-latest
    variables:
      version: $[dependencies.CalculateVersion.outputs['calculateVersion.GitVersion.SemVer']]
    steps:
     - pwsh: |
         helm registry login fsmakka.azurecr.io --username $(HELM_USER) --password $(HELM_PASSWORD)
         cd /home/vsts/work/1/s/helm
         helm dep up
         helm package .
         helm push /home/vsts/work/1/s/build/helm/charts/fsm-akka-helm-umbrella-chart-1.5.14.tgz oci://fsmakka.azurecr.io/helm