name: Publish and Prepare Environment
trigger: none

parameters:
  - name: branchName
    type: string
  - name: repoName
    type: string
  - name: serviceVersion
    type: string
  - name: umbrellaChartBaseName
    type: string

pool:
  vmImage: ubuntu-latest

variables:
  - group: HELM_VARIABLES
  - group: DOCKER_VARIABLES

resources:
  repositories:
    - repository: ServiceUmbrellaChartRepository
      type: github
      endpoint: mehmetsalgar
      name: mehmetsalgar/fsm-akka-helm-umbrella-chart-az
      ref: ${{ parameters.branchName }}
    - repository: ServiceUmbrellaChartRepositoryDevelopment
      type: github
      endpoint: mehmetsalgar
      name: mehmetsalgar/fsm-akka-helm-umbrella-chart-az
      ref: 'development'
    - repository: fsm-akka-azure-pipelines
      type: github
      name: mehmetsalgar/fsm-akka-azure-pipelines
      endpoint: mehmetsalgar

stages:
  - stage: Build
    jobs:
      - template: azure/publish-and-prepare-environment-template.yml@ServiceUmbrellaChartRepositoryDevelopment
        parameters:
          branchName: ${{ parameters.branchName }}
          repoName: ${{ parameters.repoName }}
          serviceVersion: ${{ parameters.serviceVersion }}
          umbrellaChartBaseName: ${{ parameters.umbrellaChartBaseName }}
