parameters:
  - name: branchName
    type: string
  - name: repoName
    type: string
  - name: serviceVersion
    type: string
  - name: umbrellaChartBaseName
    type: string

jobs:
  - job: CreateBranchCalculateVersion
    displayName: Create Branch Calculate Version
    steps:
      - checkout: ServiceUmbrellaChartRepository
        fetchDepth: 0
        fetchTags: true
      - task: gitversion/setup@0
        displayName: Install GitVersion
        inputs:
          versionSpec: "5.x"
      - task: gitversion/execute@0
        name: calculateVersion
        displayName: Calculating version
        inputs:
          useConfigFile: True
          configFilePath: "GitVersion.yml"
          additionalArguments: '"/b" "${{ parameters.branchName }}-${{ parameters.repoName }}"'
        env:
          IGNORE_NORMALISATION_GIT_HEAD_MOVE: 1
  - job: HelmPushServiceUmbrellaChart
    displayName: Helm Push Service Umbrella Chart
    dependsOn: CreateBranchCalculateVersion
    pool:
      vmImage: ubuntu-latest
    variables:
      version: $[dependencies.CreateBranchCalculateVersion.outputs['calculateVersion.GitVersion.SemVer']]
      service-version: ${{ parameters.serviceVersion }}
      source-repo: ${{ parameters.repoName }}
    steps:
      - checkout: ServiceUmbrellaChartRepository
      - template: helm-package-template.yml@ServiceUmbrellaChartRepositoryDevelopment
        parameters:
          command: "helmPackage -Pversion=$(version)-$(source-repo) -P$(source-repo)-version=$(service-version) --no-daemon"
      - pwsh: |
          helm registry login fsmakka.azurecr.io --username $(HELM_USER) --password $(HELM_PASSWORD)
          helm push /home/vsts/work/1/s/build/helm/charts/fsm-akka-helm-umbrella-chart-az-$(version)-$(source-repo).tgz oci://fsmakka.azurecr.io/helm
  - job: PreparingDevEnvironmentRepository
    displayName: Preparing Dev Environment Repository
    dependsOn:
      - CreateBranchCalculateVersion
      - HelmPushServiceUmbrellaChart
    variables:
      version: $[dependencies.CreateBranchCalculateVersion.outputs['calculateVersion.GitVersion.SemVer']]
      umbrella-chart-base-name: ${{ parameters.umbrellaChartBaseName }}
      service-version: ${{ parameters.serviceVersion }}
      source-repo: ${{ parameters.repoName }}
    steps:
      #Prepare Services for new Environment <-> fsm-akka-dev-environment
      - template: dispatch.yml@fsm-akka-azure-pipelines
        parameters:
          definitionId: "18"
          sourceBranch: "$(umbrella-chart-base-name)"
          inputs: '"branchName": "${{ parameters.branchName }}-$(source-repo)","tag": "$(source-repo)-$(service-version)", "version": "$(version)"'
