name: Helm Umbrella Chart Release GA
trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  - group: HELM_VARIABLES
  - group: DOCKER_VARIABLES

resources:
  repositories:
    - repository: fsm-akka-azure-pipelines
      type: github
      name: mehmetsalgar/fsm-akka-azure-pipelines
      endpoint: mehmetsalgar

stages:
  - stage: Build
    jobs:
      - job: CreateBranchCalculateVersion
        displayName: Create Branch Calculate Version
        steps:
          - checkout: self
            fetchDepth: 0
            fetchTags: true
          - task: gitversion/setup@0
            displayName: Install GitVersion
            inputs:
              versionSpec: "5.x"
          - task: gitversion/execute@0
            name: calculateVersion
            displayName: Calculating version
            inputs:
              useConfigFile: True
              configFilePath: "GitVersion.yml"
              additionalArguments: '"/b" "$(Build.SourceBranch)"'
            env:
              IGNORE_NORMALISATION_GIT_HEAD_MOVE: 1
      - job: HelmPushServiceUmbrellaChart
        displayName: Helm Push Service Umbrella Chart
        dependsOn:
          - CreateBranchCalculateVersion
        pool:
          vmImage: ubuntu-latest
        variables:
          version: $[dependencies.CreateBranchCalculateVersion.outputs['calculateVersion.GitVersion.SemVer']]
        steps:
          - checkout: self
          - template: helm-package-template.yml@self
            parameters:
              command: "helmPackage -Pversion=$(version) --no-daemon"
          - pwsh: |
              helm registry login fsmakka.azurecr.io --username $(HELM_USER) --password $(HELM_PASSWORD)
              helm push /home/vsts/work/1/s/build/helm/charts/fsm-akka-helm-umbrella-chart-az-$(version).tgz oci://fsmakka.azurecr.io/helm
