apiVersion: v2
name: fsm-akka-application
description: A Helm chart for Kubernetes
type: application
version: 1.0.0
appVersion: "${appVersion}"

dependencies:
  - name: fraud-prevention-application
    version: "${fraudPreventionVersion}"
    repository: oci://fsmakka.azurecr.io/helm
    condition: fraud-prevention.enabled